"add t0,x0 ,x0 \n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"add t1 , %[m], x0 \n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"add t2, x0 , x0 \n\t"

"reverse_loop: \n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"and t0, %[b], 1 \n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"slli t2, t2, 1 \n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"or t2, t2, t0 \n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"srli %[b], %[b], 1 \n\t"
"addi t1, t1, -1 \n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"bnez t1, reverse_loop \n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"add %[b], t2 , x0 \n\t"