"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t1, x0 , 1 \n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t2, x0 , 3 \n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t3, x0 , -1 \n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t4 , %[N] , -1 \n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"fcvt.s.w f1, t1 \n\t"
"addi %[fadd_cnt], %[fadd_cnt], 1\n\t"
"fadd.s %[pi], %[pi], f1 \n\t"

"loop: \n\t"

"addi %[others_cnt], %[others_cnt], 1\n\t"
"fcvt.s.w f2, t2 \n\t"
"addi %[fdiv_cnt], %[fdiv_cnt], 1\n\t"
"fdiv.s f2, f1, f2 \n\t"

"addi %[sub_cnt], %[sub_cnt], 1\n\t"
"bltz t3, sub \n\t"
"addi %[fadd_cnt], %[fadd_cnt], 1\n\t"
"fadd.s %[pi], %[pi], f2 \n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"j next \n\t"

"sub: \n\t"
"addi %[fsub_cnt], %[fsub_cnt], 1\n\t"
"fsub.s %[pi], %[pi], f2 \n\t"  

"next: \n\t"
"addi %[sub_cnt], %[sub_cnt], 1\n\t"
"sub t3,x0 , t3 \n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t2, t2, 2 \n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"addi t4, t4, -1 \n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
"bnez t4, loop \n\t"